stages:
  - build

build_hasura:
  stage: build
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
    - docker build -t ${CI_REGISTRY_IMAGE}:hasura-${CI_COMMIT_REF_NAME} ./hasura
    - docker push ${CI_REGISTRY_IMAGE}:hasura-${CI_COMMIT_REF_NAME}
  only:
    refs:
      - main
      - dev
    changes:
      - hasura/**/*
  tags:
    - NSCICDDOCKER
