version: "3.9"

services:
  traefik:
    command:
      - --ping
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
    ports:
      - ${TRAEFIK_PORT:-8888}:80
      - ${TRAEFIK_DASHBOARD_PORT:-8889}:8080

  db:
    ports:
      - ${DB_PORT:-5432}:5432

  graphql_engine:
    image: sonotheque-mnhn-hasura-dev
    build:
      context: ./graphql_engine
    volumes:
      - ./graphql_engine/migrations:/hasura-migrations
      - ./graphql_engine/metadata:/hasura-metadata
      - ./graphql_engine/seeds:/hasura-seeds
    environment:
      - HASURA_GRAPHQL_ENABLE_CONSOLE=true
      - HASURA_GRAPHQL_DEV_MODE=true
