SON_PK                         float64
SON_UID                         object
TYPE                            object
TITRE                           object
INSTITUTION_CODE                object
COLLECTION_CODE                 object
CATALOG_NUMBER                  object
VALIDE                         float64
VALIDE_PAR                      object
PUBLIE                         float64
DATE_PUBLICATION_DEBUT          object
DATE_PUBLICATION_FIN            object
PUBLICATION_SCIENTIFIQUE        object
RECORDER                        object
MICRO                           object
PARABOLE                       float64
FREQUENCE_ECHANTILLONNAGE      float64
SUPPORT_ORIGINAL               float64
QUALITE                        float64
DATE_ENREGISTREMENT_INT        float64
HEURE_ENREGISTREMENT_INT       float64
LIEU_ENREGISTREMENT            float64
TEMPERATURE                     object
COMMENTAIRES_ENREGISTREMENT     object
CONTEXTE_COMPORTEMENTAL         object
HABITAT                         object
DESCRIPTION_HABITAT             object
CONTINENT_OCEAN                 object
PAYS                            object
LOCALITE                        object
LATITUDE                       float64
LONGITUDE                      float64
ALTITUDE                       float64
COMMENTAIRES                    object
DATECRE                         object
DATEMAJ                         object
USERCRE                         object
USERMAJ                         object
TELECHARGER_WAV                float64
DEGRE_CERTITUDE                float64
LUMINOSITE                     float64
DROITS                          object
SON_MODE_IDENTIFICATION_PK     float64
SON_FK                         float64
MODE_IDENTIFICATION            float64
VOCABULAIRE_PK                 float64
VOCABULAIRE_CATEGORIE_FK       float64
LIBELLE_FR                      object
LIBELLE_EN                      object
OLD_PK                         float64
DATECRE2                        object
DATEMAJ3                        object
USERCRE4                        object
USERMAJ5                        object
SON_ESPECE_PK                  float64
SON_FK6                        float64
ESPECE_FK                      float64
DEGRE_CERTITUDE7               float64
DATECRE8                        object
DATEMAJ9                        object
USERCRE10                       object
USERMAJ11                       object
ESPECE_PK                      float64
VALIDE12                       float64
GROUPE_TAXONOMIQUE             float64
ORDRE                           object
FAMILLE                         object
GENRE                           object
EPITHETE_SPECIFIQUE             object
EPITHETE_INFRA_SPECIFIQUE       object
DESCRIPTEUR                     object
NOM_SCIENTIFIQUE                object
DATECRE13                       object
DATEMAJ14                       object
USERCRE15                       object
USERMAJ16                       object
NOM_VERNACULAIRE_PK            float64
ESPECE_FK17                    float64
LANG                           float64
NOM                             object
DATECRE18                       object
DATEMAJ19                       object
USERCRE20                       object
USERMAJ21                       object
VOCABULAIRE_PK22               float64
VOCABULAIRE_CATEGORIE_FK23     float64
LIBELLE_FR24                    object
LIBELLE_EN25                    object
OLD_PK26                       float64
DATECRE27                       object
DATEMAJ28                       object
USERCRE29                       object
USERMAJ30                       object
SON_AUTEUR_PK                  float64
SON_FK31                       float64
AUTEUR_FK                      float64
DATECRE32                       object
DATEMAJ33                       object
USERCRE34                       object
USERMAJ35                       object
AUTEUR_PK                      float64
NOM36                           object
DATECRE37                       object
DATEMAJ38                       object
USERCRE39                       object
USERMAJ40                       object
SON_MOT_CLE_PK                 float64
SON_FK41                       float64
MOT_CLE_FK                     float64
DATECRE42                       object
DATEMAJ43                       object
USERCRE44                       object
USERMAJ45                       object
MOT_CLE_PK                     float64
LANG46                         float64
LIBELLE                         object
DATECRE47                       object
DATEMAJ48                       object
USERCRE49                       object
USERMAJ50                       object
SON_SPECIMEN_PK                float64
SON_FK51                       float64
SPECIMEN_FK                    float64
DATECRE52                       object
DATEMAJ53                       object
USERCRE54                       object
USERMAJ55                       object
SPECIMEN_PK                    float64
INSTITUTION_CODE56              object
COLLECTION_CODE57               object
CATALOG_NUMBER58                object
DATE_COLLECTE_INT              float64
HEURE_COLLECTE_INT             float64
LUMINOSITE59                   float64
COLLECTEUR                      object
DATECRE60                       object
DATEMAJ61                       object
USERCRE62                       object
USERMAJ63                       object
FICHIER_SON_PK                 float64
SON_FK64                       float64
FICHIER_UID                     object
TYPE65                          object
PATH                            object
FILENAME                        object
MIME_TYPE                       object
TAILLE                         float64
CHECKSUM                       float64
DUREE                           object
BITSPERSAMPLE                  float64
CHANNELS                       float64
FREQUENCE_ECHANTILLONNAGE66    float64
DATECRE67                       object
DATEMAJ68                       object
USERCRE69                       object
USERMAJ70                       object
SON_IMAGE_PK                   float64
SON_FK71                       float64
IMAGE_FK                       float64
TYPE72                          object
DATECRE73                       object
DATEMAJ74                       object
USERCRE75                       object
USERMAJ76                       object
IMAGE_PK                       float64
IMAGE_UID                       object
ID                              object
MIME_TYPE77                     object
MODELE                         float64
TAILLE78                       float64
CHECKSUM79                     float64
LARGEUR                        float64
HAUTEUR                        float64
CREDIT                          object
DATECRE80                       object
DATEMAJ81                       object
USERCRE82                       object
USERMAJ83                       object